server:
  port: 9000
spring:
  application:
    name: blog-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      ## 注册中心配置
      discovery:
        # nacos的服务地址，nacos-server中IP地址:端口号
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: 3a721411-91e7-44dd-b5a8-01146ebe646e
    gateway:
      ## 路由
      routes:
        ## id只要唯一即可，名称任意
        - id: blog-user-boot
          uri: lb://blog-user-boot
          predicates:
            ## Path Route Predicate Factory断言
            - Path=/user/**
        - id: blog-auth-server
          uri: lb://blog-auth-server
          predicates:
            ## Path Route Predicate Factory断言
            - Path=/oauth/**
  redis:
    host: 127.0.01
    password:
    port: 6379
    timeout: 15000
    jedis:
      pool:
        max-active: 600
        max-idle: 300
        max-wait: 15000
        min-idle: 10

oauth:
  # JWT令牌的key
  server:
    signKey: blog
    ignore:
      urls:
        - /oauth/token
        - /oauth/authorize
